// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nrcgbbejlupiinnnkfea.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5yY2diYmVqbHVwaWlubm5rZmVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NDI3NzUsImV4cCI6MjA2NjAxODc3NX0.c8uyM5TJigy_xEPG29YfkSp7Te5QyCrv4oLGFYnIvCk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});